### ISSUE TITLE
Question about proj() transformation function

### ISSUE THREAD

**Issue by bachzz** [nishavarghese15/DRUVA#2]
Hi, thank you for your great work again !

Could you help me explain further about the fundamental theory behind the equation (3) transformation function?
![image](https://github.com/nishavarghese15/DRUVA/assets/22543582/97c2f430-fc1b-44bd-8dcc-045358c6cc55)

I have limited knowledge about two-view geometry, but I think it might be based on the "plane induced homography" from equation (13.2) in Hartley and Zisserman's "Multiple view geometry":
![image](https://github.com/nishavarghese15/DRUVA/assets/22543582/4ef8cfdb-c4af-4ae7-a9d4-1fce068691e0)

However, I am not certain about how the relative camera pose T multiplying with estimated depth map D in your equation (3) can be derived from the homography equation (13.2). 

Could you help me understand more details about the math (or in matrix representation / code implementation) behind this part?

Thank you very much !

**Comment by nishavarghese15** [comment]
Hi,

Eqn (3) is very much used in many monocular self-supervised depth estimation methods. Some example papers are [Mono2 ICCV 2019](https://openaccess.thecvf.com/content_ICCV_2019/html/Godard_Digging_Into_Self-Supervised_Monocular_Depth_Estimation_ICCV_2019_paper.html), [[CVPR 2017](https://openaccess.thecvf.com/content_cvpr_2017/html/Godard_Unsupervised_Monocular_Depth_CVPR_2017_paper.html)], [ICCV 2021](https://openaccess.thecvf.com/content/ICCV2021/html/Ji_MonoIndoor_Towards_Good_Practice_of_Self-Supervised_Monocular_Depth_Estimation_for_ICCV_2021_paper.html)

I am not exactly sure which paper derives this equation. But I tried to derive it as below.

![image](https://github.com/nishavarghese15/DRUVA/assets/93310210/ecf07356-24b6-4566-a130-8f81d1d6fc1e)

Here, the last term in the RHS of the equation has an extra row of 1s which the previous papers removed for simplicity in displaying the equation. But in their code implementation, it can be seen. 

For code implementation of warping, we used Mono2 code repository. Thanks to the authors. You can refer their [github repository ](https://github.com/nianticlabs/monodepth2). I think layers.py file has functions to do this warping and all. 


Thanks.

**Comment by bachzz** [comment]
Ah I understood better now. Thanks a lot for your references and detailed explanation !!
